### ISSUE TITLE
@Serialize.field(...) throws an error during codegen

### ISSUE THREAD

**Issue by aabluedragon** [dogma-dart/dogma-codegen#20]
Trying to codegen the following class fails:

```
class Employee {
  @Serialize.field('first_name')
  String first_name;
}
```

with error log:

```
INFO: 2016-04-16 20:19:03.127503: Rebuild requested
Unhandled exception:
The null object does not have a getter 'value'.

NoSuchMethodError: method not found: 'value'
Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:42)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:45)
#2      annotation (package:dogma_codegen/src/analyzer/annotation.dart:51:54)
#3      modelMetadata (package:dogma_codegen/src/analyzer/analyzer_metadata.dart:149:21)
#4      _libraryMetadata (package:dogma_codegen/src/analyzer/analyzer_metadata.dart:73:19)
#5      _libraryMetadata (package:dogma_codegen/src/analyzer/analyzer_metadata.dart:62:29)
#6      libraryMetadata (package:dogma_codegen/src/analyzer/analyzer_metadata.dart:32:9)
#7      build.<build_async_body> (package:dogma_codegen/build.dart:113:21)
#8      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:27)
#9      _rootRunUnary (dart:async/zone.dart:902)
#10     _CustomZone.runUnary (dart:async/zone.dart:798)
#11     _Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:553)
#12     _Future._propagateToListeners (dart:async/future_impl.dart:639)
#13     _Future._complete (dart:async/future_impl.dart:416)
#14     _SyncCompleter.complete (dart:async/future_impl.dart:52)
#15     shouldBuild.<shouldBuild_async_body> (package:dogma_codegen/src/build/build_system.dart:71:5)
#16     Future.Future.microtask.<anonymous closure> (dart:async/future.dart:144)
#17     _rootRun (dart:async/zone.dart:895)
#18     _CustomZone.run (dart:async/zone.dart:790)
#19     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:723)
#20     _microtaskLoop (dart:async/schedule_microtask.dart:41)
#21     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50)
#22     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:96)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:149)
```

Without `@Serialize.field('first_name')`, codegen works.
Dart VM version: 1.16.0-dev.5.0 (Wed Apr 13 04:15:12 2016) on "macos_x64"

**Comment by donny-dont** [comment]
I think this is around the analyzer library. Since codegen has moved quite a bit internally since the last release I will just suggest you leave out the field for now. Will revisit with you when the `0.1` release is out to make sure everything is going well.
