### ISSUE TITLE
Check if DateTime null

### ISSUE THREAD

**Issue by lejard-h** [dogma-dart/dogma-codegen#22]
`DateTime.parse()` does not support null input

``` dart
Unhandled exception:
Invalid argument(s)
#0      _RegExp.firstMatch (dart:core-patch/regexp_patch.dart:142)
#1      DateTime.parse (dart:core/date_time.dart:270)
#2      MyModelDecoder.convert (package:__projectName__/src/convert/my_model_convert.dart:33:27)
#3      MyModel.MyModel.decode (package:__projectName__/src/models/my_model.dart:18:28)
#4      main (file:///Users/lejard_h/dev/polyce/bin/template/lib/src/convert/my_model_convert.dart:57:23)
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:261)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

**Comment by donny-dont** [comment]
Hi @lejard-h I need some documentation around this but I'm going to guess that you are using the implicit serialization, meaning no `@Serialize` annotations. With implicit serialization there are no null checks, Dogma just generates code without them. If you want a null check then you need to do the following.

```
class Foo {
  @Serialize.field('bar', optional: true)
  DateTime bar;
}
```

This puts you in explicit serialization mode meaning that every field being serialized has to have an annotation on it.

**Comment by lejard-h** [comment]
Yes no `@Serialize` annotation, I did not know about it.

Now it works thanks

**Comment by lejard-h** [comment]
Sorry I spoke too fast

I have now that problem 

https://github.com/dogma-dart/dogma-codegen/issues/20
